version: '3'
services:

  auth:
    build:
      context: ./auth
      dockerfile: Dockerfile
    restart: always
    env_file:
      - ./auth/.env
    ports:
      - 3000:3000
    networks:
      - mynetwork
    depends_on:
      - auth-db

  auth-db:
    image: postgres
    restart: always
    env_file:
      - ./auth/.env
    volumes:
      - ./auth/data:/var/lib/postgresql/data
    ports:
      - 5432:5432
    networks:
      - mynetwork

networks:
  mynetwork:
    driver: bridge
